meta_product_name: "Handers"
meta_title: "Handers | Buy local, help global | The first charitable marketplace. Buy and sell products while donating to charity."
meta_description: "Buy and sell second hand products near you. The first charitable marketplace, both buyer and seller select where the money goes and benefit charitable causes. Support and increase fundraising for your favorite cause with Handers!"
meta_image: "handers.jpg" # should exist in `app/assets/images/`
